--VISTA 1  DEVOLVER ID DE AVIONES QUE AL VALIDAR LA CONFIRMACION DE VUELO FUERA PROGRAMADO punto 2
CREATE VIEW VIEW1
AS
SELECT  AVIONES.ID_AVION,VUELOS_CONFI.AVION_ID
FROM AVIONES INNER JOIN VUELOS_CONFI ON AVIONES.ID_AVION=VUELOS_CONFI.AVION_ID
WHERE VUELOS_CONFI.TYPE_ESTADO='PROGRAMADO';

SELECT * FROM VIEW1 ;
------------------------------------------------------------------------
--punto 3
--TRAE LOS TIEMPOS PARA PODER ASIGNAR LA TRIPULACION 5 HORAS ANTES 
SELECT  TO_CHAR(trunc(sysdate)+(HORA_REAL_SALIDA - TO_DATE('01/05/2018 05:00:00', 'DD/MM/YYYY HH24:MI:SS')),'HH24:MI:SS') 

 FROM VUELOS_CONFI INNER JOIN EMPLEADOS ON VUELOS_CONFI.EMPLEADO_ID=EMPLEADOS.ID_EMPLEADO ; 

--TRAER EL PRIMER AVION DE LA VISTA 
SELECT  AVION_ID  FROM VIEW1 where rownum = 1;

---ASIGNA LA TRIPULACION DEPENDIENDO DE LAS SILLAS Y LAS HORAS DE DESCANSO
SELECT  HORA_REAL_SALIDA,EMPLEADOS.NOMBRE, EMPLEADOS.HORAS_DESCANZO_ULTIMO_VUELO,CIUDADES.NOMBRE,PILOTOS.CARGO, SUM(AVIONES.CANTIDAD_PUESTOS_PREFERENCIAL + AVIONES.CANTIDAD_PUESTOS_TURISTAS) AS SILLAS
FROM VUELOS_CONFI INNER JOIN PILOTOS ON VUELOS_CONFI.PILOTO_ID= PILOTOS.ID_PILOTO INNER JOIN EMPLEADOS ON VUELOS_CONFI.EMPLEADO_ID
= EMPLEADOS.ID_EMPLEADO INNER JOIN VUELOS ON VUELOS_CONFI.VUELO_ID = VUELOS.ID_VUELO INNER JOIN AEROPUERTOS ON VUELOS.AEROPUERTO_LLEGADA_ID=AEROPUERTOS.ID_AEROPUERTO INNER JOIN 
CIUDADES ON AEROPUERTOS.CIUDAD_ID= CIUDADES.ID_CIUDAD INNER JOIN AVIONES  ON VUELOS_CONFI.AVION_ID = AVIONES.ID_AVION
WHERE  EMPLEADOS.HORAS_DESCANZO_ULTIMO_VUELO  >=  TO_DATE('01/05/2018 02:00:00', 'DD/MM/YYYY HH24:MI:SS')AND  (AVIONES.CANTIDAD_PUESTOS_PREFERENCIAL + AVIONES.CANTIDAD_PUESTOS_TURISTAS)>19 AND EMPLEADOS.ESTADO='ACTIVO' 
GROUP BY AVIONES.ID_AVION,HORA_REAL_SALIDA, EMPLEADOS.ID_EMPLEADO,PILOTOS.ID_PILOTO,EMPLEADOS.HORAS_DESCANZO_ULTIMO_VUELO,CIUDADES.NOMBRE,PILOTOS.CARGO,EMPLEADOS.NOMBRE;

---ACTUALIZA EL ESTADO 
UPDATE VUELOS_CONFI
SET ESTADO=   (SELECT ESTADO
               FROM VUELOS_CONFI INNER JOIN EMPLEADOS ON VUELOS_CONFI.EMPLEADO_ID = EMPLEADOS.ID_EMPLEADO INNER JOIN AVIONES ON 
               VUELOS_CONFI.AVION_ID =AVIONES.ID_AVION
               WHERE ESTADO='ACTIVO' AND  EMPLEADOS.HORAS_DESCANZO_ULTIMO_VUELO  >=  TO_DATE('01/05/2018 02:00:00', 'DD/MM/YYYY HH24:MI:SS')AND (AVIONES.CANTIDAD_PUESTOS_PREFERENCIAL + AVIONES.CANTIDAD_PUESTOS_TURISTAS)>19)
WHERE ESTADO= 'PROGRAMADO' ;           

---------------------------------------------------------
----- punto 4

SELECT PASAJERO_ID FROM CHECKINS INNER JOIN PASAJEROS ON CHECKINS.PASAJERO_ID =PASAJEROS.ID_PASAJERO INNER JOIN VUELOS_CONFI
ON CHECKINS.CONFIRMACION_ID = VUELOS_CONFI.ID_CONFIRMACION
WHERE VUELOS_CONFI.ID_CONFIRMACION = 1;







